# https://taskfile.dev

version: "3"

vars:
  OUT_DIR: golang
  SERVICE_NAME: todo

tasks:
  default:
    cmds:
      - mkdir -p "{{.OUT_DIR}}/{{.SERVICE_NAME}}"
      - >-
        protoc --go_out={{.OUT_DIR}} \
          --go_opt=paths=source_relative \
          --go-grpc_out={{.OUT_DIR}} \
          --go-grpc_opt=paths=source_relative \
          ./{{.SERVICE_NAME}}/*.proto
      - >-
        cd {{.OUT_DIR}}/{{.SERVICE_NAME}} && go mod init github.com/kameshsampath/demo-protos/golang/{{.SERVICE_NAME}} || true
      - cd {{.OUT_DIR}}/{{.SERVICE_NAME}} && go mod tidy
    silent: true
